config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: 'admin',
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions',
             }, skip: [:sessions]

 as :user do
   get 'login' => 'users/sessions#new', as: :new_user_session
   post 'login' => 'users/sessions#create', as: :user_session
   delete 'logout' => 'users/sessions#destroy', as: :destroy_user_session
   get 'register' => 'users/registrations#new'
 end

  namespace :admin do
    resources :announcements
    resources :vehicles do
      resources :photos
    end
    resources :settings
  end

  resources :announcements, only: [:index, :show]

  resources :vehicles do
    resources :photos, only: [:index, :show]
    collection do
      get :search
      get :autocomplete
    end
  end

  get 'admin' => 'admin/vehicles#index'
  root 'listings#index'
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  mount_uploaders :photos, PhotoUploader

  searchkick word_start: [:make, :model, :year]
  # searchkick text_start: [:make, :model, :year]
  default_scope { order(created_at: :desc) }
end

app/controllers/admin/vehicles_controller.rb
class Admin::VehiclesController < Admin::AdminController
  expose(:vehicle, attributes: :vehicle_params)
  expose(:vehicle_photos) { vehicle.photos.each { |photo| photo.large.url } }
  expose(:admin_vehicles) { Vehicle.all }

  def create
    if vehicle.save
      redirect_to admin_vehicle_path(vehicle)
    else
      render :new
    end
  end

  def update
    if vehicle.save
      redirect_to admin_vehicles_path
    else
      render :edit
    end
  end

  def destroy
    vehicle.remove_photos
    vehicle.destroy
    redirect_to admin_path
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:make, :model, :trim, :year, :vin, :price,
                                      :doors, :engine, :transmission, :int_color,
                                      :ext_color, :description, :warranty, :sold,
                                      :warranty_type, :used, :new, :featured,
                                      :interior_type, :mileage, photos: [])
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  expose(:vehicle) { Vehicle.find(params[:id]) }
  expose(:vehicle_photos) { vehicle.photos.each { |photo| photo.large.url } }
  expose(:vehicles) { Vehicle.search(vehicle_query, fields: [:make, :model, :year], match: :word_start) }
  expose(:vehicle_query) { params[:query].presence || '*' }

  def create
    if vehicle.save
      redirect_to vehicle
    else
      render :new
    end
  end

  def search
    if params[:query].present?
      vehicles
    else
      Vehicle.all
    end
  end

  def autocomplete
   render json: Vehicle.search(params[:term], {
                               fields: ["make", "model", "year"],
                               limit: 10}).map(&:make).uniq
  end

end

app/views/admin/vehicles/_form.html.haml
.row
  .col-md-4
    .form-group
      %label Price
      = form.text_field :price, placeholder:'Price', type: 'text', value: vehicle.price, class: 'form-control'
  .col-md-4
    .form-group
      %label VIN
      = form.text_field :vin, placeholder:'VIN', type: 'text', value: vehicle.vin, class: 'form-control'
.row
  .col-md-3
    .form-group
      %label Year
      = form.text_field :year, placeholder:'Year', type: 'text', value: vehicle.year, class: 'form-control'
  .col-md-3
    .form-group
      %label Make
      = form.text_field :make, placeholder:'Make', type: 'text', value: vehicle.make, class: 'form-control'
  .col-md-3
    .form-group
      %label Model
      = form.text_field :model, placeholder:'Model', type: 'text', value: vehicle.model, class: 'form-control'
  .col-md-3
    .form-group
      %label Trim
      = form.text_field :trim, placeholder:'Trim', type: 'text', value: vehicle.trim, class: 'form-control'
.row
  .col-md-3
    .form-group
      %label Mileage
      = form.text_field :mileage, placeholder:'Mileage', type: 'text', value: vehicle.mileage, class: 'form-control'
  .col-md-3
    .form-group
      %label Exterior Color
      = form.text_field :ext_color, placeholder:'Exterior Color', type: 'text', value: vehicle.ext_color, class: 'form-control'
  .col-md-3
    .form-group
      %label Interior Color
      = form.text_field :int_color, placeholder:'Interior Color', type: 'text', value: vehicle.int_color, class: 'form-control'
  .col-md-3
    .form-group
      %label Type of Interior
      = form.text_field :interior_type, placeholder:'Type of Interior', type: 'text', value: vehicle.interior_type, class: 'form-control'
.row
  .col-md-3
    .form-group
      %label Doors
      = form.text_field :doors, placeholder:'Doors', type: 'text', value: vehicle.doors, class: 'form-control'
  .col-md-3
    .form-group
      %label Engine
      = form.text_field :engine, placeholder:'Engine', type: 'text', value: vehicle.engine, class: 'form-control'
  .col-md-3
    .form-group
      %label Transmission
      = form.text_field :transmission, placeholder:'Transmission', type: 'text', value: vehicle.transmission, class: 'form-control'
.row
  .col-md-3
    .form-group
      %label Does Vehicle have a Warranty
      = form.check_box :warranty, value: false, class: 'form-control'
  .col-md-3
    .form-group
      %label Type of Warranty
      = form.text_field :warranty_type, placeholder:'Type of Warrabty', type: 'text', value: vehicle.warranty_type, class: 'form-control'
.row
  .col-md-12
    .form-group
      %label Description
      = form.text_area :description, placeholder: "Enter other information about the Vehicle Here", rows: "5", value: vehicle.description, class: 'form-control'
.row
  .col-md-3
    .form-group
      %label Is this Vehicle New
      = form.check_box :new, class: 'form-control'
  .col-md-3
    .form-group
      %label Is this Vehicle Used
      = form.check_box :used, class: 'form-control'
  .col-md-3
    .form-group
      %label Is this a Featured Vehicle
      = form.check_box :featured, class: 'form-control'
  .col-md-3
    .form-group
      %label Is this Vehicle Sold
      = form.check_box :sold, class: 'form-control'

app/views/admin/vehicles/_photo_upload.html.haml
.row
  = form_for [:admin, vehicle], url: admin_vehicle_photos_path(vehicle), method: :post, html: { multipart: true } do |photo_form|
    .col-md-8
      .card
        .header
          %h4.title Vehicle Photos
        .content
          .row
            - vehicle.photos.each_with_index do |image, index|
              .col-md-4.vdp
                = image_tag(image.thumb.url)
                .vdp
                  = link_to 'Delete', admin_vehicle_photo_path(vehicle, index),
                    class: 'btn btn-danger btn-fill btn-sm',
                    method: :delete,
                    data: { confirm: 'Are you sure you want to delete this image?' }
          .row.vdp
            .col-md-4
              %label 'Upload Photos'
              = photo_form.file_field :photos, multiple: true
            .col-md-4.pull-right
              = photo_form.submit 'Update Vehicle Photos', class: 'btn btn-info btn-fill pull-right'

app/views/admin/vehicles/edit.html.haml
= render "photo_upload"
.row
  = form_for [:admin, vehicle] do |form|
    .col-md-8
      .card
        .header
          %h4.title Edit Vehicle Information
        .content
          %form
            = render 'form', form: form
          .clearfix
            = form.submit 'Update Vehicle', class: 'btn btn-info btn-fill pull-right'

app/views/admin/vehicles/index.html.haml
- if user_signed_in?
  .row.vdp
    .col-md-6
      %h3
        = link_to "Add Vehicle", new_admin_vehicle_path, class: 'btn btn-success btn-fill'
.flex-box.row.vdp
  - admin_vehicles.each do |vehicle|
    .col-md-4.vdp
      - if vehicle.photos?
        = link_to image_tag(vehicle.photos.first.thumb.url, class: 'thumbnail'), admin_vehicle_path(vehicle)
      - else
        = link_to image_tag('no_image_available-thumb', class: 'thumbnail'), admin_vehicle_path(vehicle)
      %h5
        = "#{vehicle.year} #{vehicle.make} #{vehicle.model} #{vehicle.trim}"
      %p
        = "#{number_to_currency(vehicle.price)}"
      = link_to 'View Details', admin_vehicle_path(vehicle), class: 'btn btn-info btn-fill expaneded'

app/views/admin/vehicles/new.html.haml
.row
  = form_for [:admin, vehicle] do |form|
    .col-md-8
      .card
        .header
          %h4.title Vehicle Photos
        .content
          .row.vdp
            .col-md-4
              %label 'Upload Photos'
              = form.file_field :photos, multiple: true
    .col-md-8
      .card
        .header
          %h4.title Add a Vehicle
        .content
          %form
            = render 'form', form: form
          .clearfix
            = form.submit 'Save Vehicle', class: 'btn btn-info btn-fill pull-right'

app/views/admin/vehicles/search.html.haml
.row.small-up-2.large-up-4.vdp
  - vehicles.each do |vehicle|
    .column
      - if vehicle.photos?
        = link_to image_tag(vehicle.photos.first.large.url, class: 'thumbnail'), vehicle
      - else
        = link_to image_tag('no_image_available.jpeg', class: 'thumbnail'), vehicle
      %h5
        = "#{vehicle.year} #{vehicle.make} #{vehicle.model} #{vehicle.trim}"
      %p
        = "#{number_to_currency(vehicle.price)}"
      = link_to 'View Details', vehicle, class: 'button expaneded'

app/views/admin/vehicles/show.html.haml
.row
  .col-md-6
    - if user_signed_in?
      .row
        .col-md-8
          = link_to 'Edit', edit_admin_vehicle_path(vehicle), class: 'btn btn-warning btn-fill'
          = link_to 'Destroy', admin_vehicle_path(vehicle), class: 'btn btn-danger btn-fill', method: :delete, data:{confirm:"are you sure you want to delete this vehicle"}
.row.vdp
  .col-md-12
    .card
      .content
        %p
          = vehicle.description? ? vehicle.description : "No Description Available for this Vehicle"
  .col-md-8
    - if vehicle.photos.presence
      = carousel_for(vehicle_photos)
      .row.vdp
        - vehicle.photos.each do |photo|
          .col-md-4
            = image_tag photo.thumb.url, class: 'thumbnail img-responsive'
    - else
      = image_tag 'no_image_available.jpeg', class: 'thumbnail img-responsive'

  .col-md-4
    .card
      .content
        %h3
          = "#{vehicle.year} #{vehicle.make} #{vehicle.model} #{vehicle.trim}"
        %h5
          = "#{number_to_currency(vehicle.price)}"
        .row
          .col-md-6
            %h4 Details
        .row
          .col-md-12
            %ul
              %li= "Mileage: #{vehicle.mileage}"
              %li= "Engine: #{vehicle.engine}"
              %li= "Transmission: #{vehicle.transmission}"
              %li= "Exterior Color: #{vehicle.ext_color}"
              %li= "Interior Color: #{vehicle.int_color}"
              %li= "VIN: #{vehicle.vin}"