config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: 'admin',
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions',
             }, skip: [:sessions]

 as :user do
   get 'login' => 'users/sessions#new', as: :new_user_session
   post 'login' => 'users/sessions#create', as: :user_session
   delete 'logout' => 'users/sessions#destroy', as: :destroy_user_session
   get 'register' => 'users/registrations#new'
 end

  namespace :admin do
    resources :announcements
    resources :vehicles do
      resources :photos
    end
    resources :settings
  end

  resources :announcements, only: [:index, :show]

  resources :vehicles do
    resources :photos, only: [:index, :show]
    collection do
      get :search
      get :autocomplete
    end
  end

  get 'admin' => 'admin/vehicles#index'
  root 'listings#index'
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  validates :title, :body, presence: true
end

app/controllers/admin/announcements_controller.rb
class Admin::AnnouncementsController < Admin::AdminController
  expose(:announcement, attributes: :announcement_params)
  expose(:announcements)

  def create
    if announcement.save
      redirect_to admin_path
    else
      render :new
    end
  end

  def update
    if announcement.save
      redirect_to admin_path
    else
      render :edit
    end
  end

  private

  def announcement_params
    params.require(:announcement).permit(:title, :body)
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  expose(:announcement, attributes: :announcement_params)
  expose(:announcements)
  before_action :authenticate_user!, except: :show

  def create
    if announcement.save
      redirect_to announcements_path
    else
      render :new
    end
  end

  def update
    if announcement.save
      redirect_to announcements_path
    else
      render :edit
    end
  end

  private

  def announcement_params
    params.require(:announcement).permit(:title, :body)
  end
end

app/views/admin/announcements/_form.html.haml
.row
  .col-md-12
    .form-group
      %label Announcement Title
      = form.text_field :title, placeholder: "Announcement Title", value: announcement.title, class: 'form-control'
  .col-md-12
    .form-group
      %label Announcement Message
      = form.text_area :body, placeholder: "Enter your Announcement Message here", rows: "8", value: announcement.body, class: 'form-control'

app/views/admin/announcements/edit.html.haml
.row
  = form_for [:admin, announcement] do |form|
    .col-md-8
      .card
        .header
          %h4.title Edit Announcement
        .content
          %form
            = render 'form', form: form
          .clearfix
            = form.submit 'Update Announcement', class: 'btn btn-info btn-fill pull-right'

app/views/admin/announcements/index.html.haml
.col-md-12
  .card
    .header
      %h4.title Announcements
      = link_to 'Add Announcement', new_admin_announcement_path, class: 'btn btn-success btn-fill'

    .content
      .table-full-width
        %table.table
          %tbody
            - announcements.each do |announcement|
              %tr
                %td
                %td= announcement.title
                %td.td-actions.text-right
                  = link_to 'Edit Announcement', edit_admin_announcement_path(announcement), class: 'btn btn-primary btn-simple', title: 'Edit Announcement'
                  = link_to 'Destroy', admin_announcement_path(announcement), class: 'btn btn-danger btn-simple', title: 'Remove', method: :delete, data:{confirm:'Are you sure you want to delete this Announcement'}

app/views/admin/announcements/new.html.haml
.row
  = form_for [:admin, announcement] do |form|
    .col-md-8
      .card
        .header
          %h4.title Create an Announcement
        .content
          %form
            = render 'form', form: form
          .clearfix
            = form.submit 'Save Announcement', class: 'btn btn-info btn-fill pull-right'

app/views/admin/announcements/show.html.haml
.row
  .small-12.medium-6.large-12
    = announcement.title
    %hr
    = announcement.body