config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: 'admin',
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions',
             }, skip: [:sessions]

 as :user do
   get 'login' => 'users/sessions#new', as: :new_user_session
   post 'login' => 'users/sessions#create', as: :user_session
   delete 'logout' => 'users/sessions#destroy', as: :destroy_user_session
   get 'register' => 'users/registrations#new'
 end

  namespace :admin do
    resources :announcements
    resources :vehicles do
      resources :photos
    end
    resources :settings
  end

  resources :announcements, only: [:index, :show]

  resources :vehicles do
    resources :photos, only: [:index, :show]
    collection do
      get :search
      get :autocomplete
    end
  end

  get 'admin' => 'admin/vehicles#index'
  root 'listings#index'
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::AdminController
  expose(:settings)
  expose(:setting, attributes: :setting_params)

 def create
    if setting.save
      redirect_to admin_path
    else
      render :new
    end
  end

  def update
    if setting.save
      redirect_to admin_path
    else
      render :edit
    end
  end

  private

  def setting_params
    params.require(:setting).permit(:footer)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/admin/settings/_form.html.haml
.row
  .col-md-12
    .form-group
      %label Footer Content
      = form.text_area :footer, placeholder: "Enter your Footer information here", rows: "8", value: setting.footer, class: 'form-control'

app/views/admin/settings/edit.html.haml
.row
  = form_for [:admin, setting] do |form|
    .col-md-8
      .card
        .header
          %h4.title Edit Footer Setting
        .content
          %form
            = render 'form', form: form
          .clearfix
            = form.submit 'Update Footer', class: 'btn btn-info btn-fill pull-right'

app/views/admin/settings/index.html.haml
.col-md-12
  .card
    .header
      %h4.title Site Settings

    .content
      .table-full-width
        %table.table
          %tbody
            - settings.each do |setting|
              %tr
                %td
                %td= setting.footer
                %td.td-actions.text-right
                  = link_to 'Edit Footer', edit_admin_setting_path(setting), class: 'btn btn-primary btn-simple', title: 'Edit Footer'

                %td.td-actions.text-right
                  = link_to 'Destroy', admin_setting_path(setting), class: 'btn btn-danger btn-simple', title: 'Remove', method: :delete, data:{confirm:'Are you sure you want to delete Footer text?'}