config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: 'admin',
             controllers: {
               registrations: 'users/registrations',
               sessions: 'users/sessions',
             }, skip: [:sessions]

 as :user do
   get 'login' => 'users/sessions#new', as: :new_user_session
   post 'login' => 'users/sessions#create', as: :user_session
   delete 'logout' => 'users/sessions#destroy', as: :destroy_user_session
   get 'register' => 'users/registrations#new'
 end

  namespace :admin do
    resources :announcements
    resources :vehicles do
      resources :photos
    end
    resources :settings
  end

  resources :announcements, only: [:index, :show]

  resources :vehicles do
    resources :photos, only: [:index, :show]
    collection do
      get :search
      get :autocomplete
    end
  end

  get 'admin' => 'admin/vehicles#index'
  root 'listings#index'
end

app/views/layouts/application.html.haml
!!! 5
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }

    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }

    %title= Settings.title? ? 'Easylot' : Settings.title

    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag

  %body
    = render 'shared/gtm'
    = render 'shared/navigation'
    .container.vdp
      = yield

    = render 'shared/footer'

app/views/layouts/dashboard.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %link{:href => "assets/img/favicon.ico", :rel => "icon", :type => "image/png"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title= Settings.title? ? 'Easylot' : Settings.title + " powered by EasyLot"
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}/
    %meta{:content => "width=device-width", :name => "viewport"}/
    = javascript_include_tag 'application'
    = csrf_meta_tag
    / Bootstrap core CSS
    = stylesheet_link_tag 'application'

    %link{:href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Roboto:400,700,300", :rel => "stylesheet", :type => "text/css"}/

  %body
    .wrapper
      .sidebar{"data-color" => "black", "data-image" => "#{image_path('sidebar-5.jpg')}"}
        /
          Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
          Tip 2: you can also add an image using data-image tag
        .sidebar-wrapper
          .logo
            %a.simple-text{:href => "#{admin_path}"}
              J.R. Jackson Auto Sales
              %br/
              %h6
                powered by EasyLot
          %ul.nav
            %li.active
              = link_to 'Dashboard', admin_path
            %li
              = link_to 'Account Settings', edit_user_registration_path
            %li
              = link_to 'Site Settings', admin_settings_path
            %li
              = link_to 'Announcements', admin_announcements_path
            %li
              = link_to 'Vehicles', admin_vehicles_path

      .main-panel
        %nav.navbar.navbar-default.navbar-fixed
          .container-fluid
            .navbar-header
              %button.navbar-toggle{"data-target" => "#navigation-example-2", "data-toggle" => "collapse", :type => "button"}
                %span.sr-only Toggle navigation
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
              %a.navbar-brand{:href => "#"} Dashboard
            .collapse.navbar-collapse
              %ul.nav.navbar-nav.navbar-left
                %li
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    %i.fa.fa-dashboard

              %ul.nav.navbar-nav.navbar-right
                %li
                  = link_to "Account Settings", edit_user_registration_path

                %li
                  = link_to 'Logout', destroy_user_session_path, method: :delete
        .content
          .container-fluid
            .row
              .col-md-12
                = yield

        %footer.footer
          .container-fluid
            %p.copyright.pull-right
              &copy; #{Time.now.year} J.R. Jackson Auto Sales powered by EasyLot

app/views/layouts/sessions.html.haml
!!! 5
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }

    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }

    %title= Settings.title? ? 'Easylot' : Settings.title

    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag

  %body
    .row
      .container
        .col-md-10
          = form_for(resource, as: resource_name, url: session_path(resource_name), class: 'form-signin') do |f|
            %h4.form-signin-heading Login using your email
            %label.sr-only{:for => "inputEmail"} Email address
            = f.email_field :email, autofocus: true, id: 'inputEmail', class: 'form-control', placeholder: 'Email Address', require: "", type: 'email'
            %label.sr-only{:for => "inputPassword"} Password
            = f.password_field :password, id: 'inputPassword', class: 'form-control', autocomplte: 'off', required: '', type: 'password'
            - if devise_mapping.rememberable?
              = f.check_box :remember_me
              = f.label :remember_me
            %p
              = f.submit "Log in", class: "btn btn-lg btn-primary btn-block"
            = render "devise/shared/links"